Okty-io/okty

angular.json
package-lock.json
package.json
src/app/app.component.html
src/app/app.module.ts
src/app/components/notification/notification.component.html
src/app/components/notification/notification.component.scss
src/app/components/notification/notification.component.ts
src/app/components/review/review.component.html
src/app/components/review/review.component.scss
src/app/components/setup/setup.component.ts
src/app/services/message.service.ts

In reference to : https://github.com/lbassin/okty/issues/45

Review page enhancements

---

src/app/components/notification/notification.component.ts
src/app/components/setup/form/input/input.component.html
src/app/components/setup/form/input/input.component.scss
src/app/components/setup/form/select-container/select-container.component.html
src/app/components/setup/form/select/select.component.html
src/app/components/setup/form/selectize/selectize.component.html
src/app/components/setup/setup.component.scss
src/app/components/setup/setup.component.ts

Add red color on error label and display notification error on submit

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
src/app/components/home/home.component.html
src/app/components/review/review.component.ts
src/app/components/setup/setup.component.ts
src/index.html

Please describe what behaviour may be affected by your code
Please describe the steps to verify your changes. 

English check

---

src/app/components/review/review.component.ts
src/index.html

Redirect if review empty

---

src/app/components/sidebar/sidebar.component.html

Add "Go to review" button in sidebar

---

src/app/app.module.ts
src/app/components/setup/setup.component.ts
src/app/pipes/validator-errors.pipe.ts
src/app/services/project.service.ts
src/app/validators/container.validator.ts

Prevent user to have duplicated container ID
Fixes #80

Duplicate container ID #80

---

src/app/components/setup/setup.component.html
src/app/components/setup/setup.component.scss
src/app/components/setup/setup.component.ts
src/app/components/sidebar/sidebar.component.html
src/app/components/sidebar/sidebar.component.scss
src/app/components/sidebar/sidebar.component.ts

74 remove container

---

src/app/components/setup/setup.component.ts
src/app/services/edit-container.resolve.ts
src/app/services/project.service.ts

#80 Fix unique id error when editing container

---

src/app/components/setup/setup.component.ts
src/app/components/sidebar/sidebar.component.html
src/app/services/edit-container.resolve.ts
src/app/services/project.service.ts
src/app/validators/container.validator.ts

#80 Fix new container when edit an existing one

---

src/index.html

Fix og meta

---

src/app/components/template/template.component.ts

#91 Fix home redirection

---

src/index.html
src/manifest.json

#73 Fix theme color

---

src/app/components/home/home.component.html
src/app/components/home/home.component.scss
src/app/components/search/search.component.scss

#73 Remove shadow

---

src/app/components/home/home.component.scss
src/app/components/search/search.component.scss

Fix logo alignment in okty containers cars && add media query for the container's home

---

src/app/components/search/search.component.html
src/app/components/search/search.component.scss
src/app/components/setup/form/multi-select/multi-select.component.ts

Add twitter link

---

src/app/app.component.html

Add doc link

---

CONTRIBUTING.md
README.md
src/app/app.component.html
src/app/app.vars.ts
src/app/components/search/search.component.html

Move GitHub

---

CONTRIBUTING.md
package-lock.json
src/app/app.component.html
src/app/components/home/home.component.html
src/app/components/review/review.component.html
src/app/components/search/search.component.html

Updated links to our new twitter username & little href changes

Twitter links updated & few word changes

---

.travis.yml
package.json

Fix npm start command (Not working with docker-environment)

---

src/app/services/container.service.ts

Fix error when running multiple command 

Fix error on command override

---

.travis.yml

Update firebase token

---

src/app/components/setup/form/multi-select/multi-select.component.ts
src/app/components/setup/form/select/select.component.ts
src/app/services/api.service.ts

Fix missing data from api (source on select)

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md

DOC updates due to new features, team changes and to make it easier to contribute.

[DOC] - Contributing & Pull Requests & ReadMe

---

.travis.yml

Deploy to AWS

---

src/app/core/services/api.service.ts
src/environments/environment.dev.ts
src/environments/environment.prod.ts

Fix API url

---

src/app/modules/generator/repositories/project.repository.ts
src/app/modules/generator/repositories/template.repository.ts

Fix routes

---

src/app/modules/users/guards/isLoggedIn.ts
src/app/modules/users/users-routing.module.ts

Reject profile route if not logged in

---

src/app/modules/generator/repositories/container.repository.ts

Update container route

---

src/app/core/services/api.service.ts

Remove JWT token if expired

---

src/app/modules/users/pages/login/login.component.html
src/app/modules/users/pages/login/login.component.ts
src/app/modules/users/pages/oauth/oauth.component.ts
src/environments/environment.dev.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Gitlab auth

---

docker-compose.yaml
package-lock.json
package.json

Add local dev

---

src/app/modules/home/components/page-illustration/page-illustration.component.html
src/app/modules/home/components/page-illustration/page-illustration.component.scss
src/app/modules/home/components/page-illustration/page-illustration.component.spec.ts
src/app/modules/home/components/page-illustration/page-illustration.component.ts
src/app/modules/home/home.module.ts
src/app/modules/home/pages/home/home.component.html
src/app/modules/home/pages/home/home.component.scss

illustration component done

---

src/app/modules/generator/components/review-grid/review-grid.component.html
src/app/modules/generator/components/review-grid/review-grid.component.scss

Fixing the CSS box image of containers in the page review. 
- [ X ] Bug fix

Fixing image-box sizing on page review

---

src/app/modules/generator/components/form-action/form-action.component.html
src/app/modules/generator/components/form-action/form-action.component.scss

Change button position

---

src/app/modules/generator/generator-routing.module.ts
src/app/modules/generator/generator.module.ts
src/app/modules/generator/guards/leave.guard.ts

Ask confirmation before leaving generator

Ask confirmation before leaving generator

---

src/app/modules/generator/components/review-grid/review-grid.component.scss

Remove default link color on review page

---

src/app/modules/generator/services/container.service.ts
src/app/modules/generator/validators/container.validators.ts

Allow empty port

---

src/app/core/components/footer/footer.component.html
src/app/core/components/footer/footer.component.scss
src/app/core/components/footer/footer.component.ts

Add links in footer

---

src/app/modules/generator/generator-routing.module.ts
src/app/modules/generator/generator.module.ts
src/app/modules/generator/guards/leave.guard.ts
src/app/modules/generator/pages/load/load.component.ts

Reset session after leaving generator

---

src/app/modules/generator/validators/container.validators.ts

Fix unique id validator

---

src/app/modules/generator/components/list/list.component.scss

Remove css warning

---

src/app/modules/cms/components/page-illustration/page-illustration.component.ts
src/app/modules/cms/pages/home/home.animation.ts
src/app/modules/cms/pages/home/home.component.html
src/app/modules/cms/pages/home/home.component.scss
src/app/modules/cms/pages/home/home.component.ts
src/app/modules/generator/components/card/card.component.ts

Responsive home

---

src/app/modules/generator/components/card/card.component.scss
src/app/modules/generator/components/form/form.component.scss
src/app/modules/generator/components/list/list.component.html
src/app/modules/generator/components/list/list.component.scss
src/app/modules/generator/components/search/search.component.scss
src/app/modules/generator/components/sidebar/sidebar.component.scss
src/app/modules/generator/pages/add/add.component.html
src/app/modules/generator/pages/add/add.component.scss
src/app/modules/generator/pages/containers/containers.component.scss
src/assets/style/media-query.scss

Responsive

---

src/app/core/components/navbar/navbar.component.html
src/app/core/components/navbar/navbar.component.scss
src/app/modules/cms/components/page-illustration/page-illustration.component.ts
src/app/modules/generator/components/list/list.component.html
src/app/modules/generator/components/list/list.component.scss
src/app/modules/generator/components/review-grid/review-grid.component.scss
src/app/modules/generator/components/search/search.component.scss
src/app/modules/generator/pages/add/add.component.html
src/app/modules/generator/pages/add/add.component.scss
src/app/modules/generator/pages/add/add.component.ts
src/app/modules/generator/pages/containers/containers.component.scss
src/app/modules/generator/pages/edit/edit.component.html
src/app/modules/generator/pages/edit/edit.component.scss
src/app/modules/generator/pages/edit/edit.component.ts
src/app/modules/generator/pages/review/review.component.scss
src/app/shared/components/loader.component.scss
src/app/shared/components/loader.component.ts
src/app/shared/shared.module.ts

Improve responsive

---

src/app/core/components/navbar/navbar.component.html
src/app/core/components/navbar/navbar.component.scss
src/app/modules/generator/components/card/card.component.scss
src/app/modules/generator/components/list/list.component.html
src/app/modules/generator/components/list/list.component.scss
src/app/modules/generator/components/list/list.component.ts

Fix design

---

src/app/modules/generator/components/review-action/review-action.component.scss
src/app/modules/generator/components/review-grid/review-grid.component.scss
src/app/modules/generator/pages/review/review.component.scss
src/assets/style/highlight.scss

Review page on mobile

---

src/app/modules/cms/components/page-illustration/page-illustration.component.ts

responsiveness of page illustration

---

src/app/modules/generator/components/review-action/review-action.component.html
src/app/modules/generator/components/review-action/review-action.component.ts
src/app/modules/generator/pages/edit/edit.component.html
src/app/shared/components/loader.component.ts

Add loader on review

---

src/app/modules/generator/pages/add/add.component.scss
src/app/modules/generator/pages/edit/edit.component.scss

Setup on mobile

---

.firebaserc
firebase.json

Fix firebase

---

.firebaserc
.travis.yml
firebase.json

Fix template generation

---

src/app/modules/learning/components/lesson-card/lesson-card.component.ts
src/app/modules/learning/pages/lesson/lesson.component.ts

Save learning progress

---

src/app/core/components/navbar/navbar.component.html

Hide navbar

---

src/app/core/components/footer/footer.component.html
src/app/core/components/navbar/navbar.component.html

Fix footer

---

src/environments/environment.dev.ts
src/environments/environment.prod.ts

Fix cookie consent domain

---

src/app/core/configs/cookie-consent.ts

Fix cookie consent

---

src/app/modules/cms/pages/privacy/privacy.component.html
src/app/modules/cms/pages/privacy/privacy.component.scss

Update of Privacy content according to collected information.
- [ X ] New feature

Add of Privacy content

---

src/app/core/configs/cookie-consent.ts
src/app/modules/cms/pages/privacy/privacy.component.html
src/app/modules/cms/pages/privacy/privacy.component.scss

Add privacy

---

src/app/modules/generator/components/card/card.component.html
src/app/modules/generator/components/card/card.component.ts

fix untrsuted svg url resource
